#!/usr/bin/env python3
"""Generate the sample/test 3D models for 3d-book.

This produces a small textured cube in two formats so the app (and the loader
unit tests) have real assets to exercise both code paths:

  - Wavefront OBJ  : <name>.obj + <name>.mtl + <name>.png  (external texture)
  - Binary glTF    : <name>.glb                            (embedded texture)

It deliberately uses only the Python standard library (zlib/struct/json) so it
needs no third-party packages. Re-run it to regenerate the committed assets:

    python3 tools/make_sample_models.py

Outputs land in  models/  (shipped next to the app) and  tests/assets/
(fixtures for the headless loader tests).
"""
import json
import os
import struct
import zlib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# --- PNG writer (RGBA8) ----------------------------------------------------
def make_png(width, height, rgba_at):
    """Return PNG bytes for an image whose pixel (x,y) = rgba_at(x, y) -> (r,g,b,a)."""
    raw = bytearray()
    for y in range(height):
        raw.append(0)  # filter type 0 (None) per scanline
        for x in range(width):
            raw.extend(rgba_at(x, y))

    def chunk(tag, data):
        out = struct.pack(">I", len(data)) + tag + data
        crc = zlib.crc32(tag + data) & 0xFFFFFFFF
        return out + struct.pack(">I", crc)

    sig = b"\x89PNG\r\n\x1a\n"
    ihdr = struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0)  # 8-bit RGBA
    idat = zlib.compress(bytes(raw), 9)
    return sig + chunk(b"IHDR", ihdr) + chunk(b"IDAT", idat) + chunk(b"IEND", b"")


def quadrant_texture(palette, size=64):
    """A four-colored, grid-lined, white-bordered texture.

    The four quadrants use distinct colors so a flipped/upside-down mapping is
    immediately obvious; the (0,0) origin sits at the top-left of the image.
    """
    tl, tr, bl, br = palette

    def at(x, y):
        if x < 2 or y < 2 or x >= size - 2 or y >= size - 2:
            return (245, 245, 245, 255)        # white border
        if x % 16 == 0 or y % 16 == 0:
            return (40, 40, 40, 255)            # dark grid lines
        top = y < size // 2
        left = x < size // 2
        return (tl if left else tr) + (255,) if top else (bl if left else br) + (255,)

    return make_png(size, size, at)


# --- Cube geometry ---------------------------------------------------------
# 6 faces x 4 corners, with per-face normals and a full 0..1 UV square per face.
# Winding is consistent CCW-outward, though the renderer draws double-sided.
def cube():
    h = 0.5
    faces = [
        # (normal, [4 corners CCW from outside])
        ((1, 0, 0),  [(h, -h, h), (h, -h, -h), (h, h, -h), (h, h, h)]),     # +X
        ((-1, 0, 0), [(-h, -h, -h), (-h, -h, h), (-h, h, h), (-h, h, -h)]), # -X
        ((0, 1, 0),  [(-h, h, h), (h, h, h), (h, h, -h), (-h, h, -h)]),     # +Y
        ((0, -1, 0), [(-h, -h, -h), (h, -h, -h), (h, -h, h), (-h, -h, h)]), # -Y
        ((0, 0, 1),  [(-h, -h, h), (h, -h, h), (h, h, h), (-h, h, h)]),     # +Z
        ((0, 0, -1), [(h, -h, -h), (-h, -h, -h), (-h, h, -h), (h, h, -h)]), # -Z
    ]
    uv = [(0, 0), (1, 0), (1, 1), (0, 1)]
    positions, normals, uvs, indices = [], [], [], []
    for n, corners in faces:
        base = len(positions)
        for i, c in enumerate(corners):
            positions.append(c)
            normals.append(n)
            uvs.append(uv[i])
        indices += [base, base + 1, base + 2, base, base + 2, base + 3]
    return positions, normals, uvs, indices


# --- OBJ writer ------------------------------------------------------------
def write_obj(stem, png_bytes, palette):
    positions, normals, uvs, indices = cube()
    name = os.path.basename(stem)
    obj = [f"# textured cube — generated by tools/make_sample_models.py",
           f"mtllib {name}.mtl", "o textured_cube"]
    for p in positions:
        obj.append(f"v {p[0]:.4f} {p[1]:.4f} {p[2]:.4f}")
    for t in uvs:
        obj.append(f"vt {t[0]:.4f} {t[1]:.4f}")
    for n in normals:
        obj.append(f"vn {n[0]:.1f} {n[1]:.1f} {n[2]:.1f}")
    obj.append(f"usemtl cube_mat")
    # OBJ is 1-indexed; v/vt/vn share the same index here (one vertex per corner).
    for i in range(0, len(indices), 3):
        a, b, c = indices[i] + 1, indices[i + 1] + 1, indices[i + 2] + 1
        obj.append(f"f {a}/{a}/{a} {b}/{b}/{b} {c}/{c}/{c}")

    mtl = ["# generated material", "newmtl cube_mat",
           "Ka 0.0 0.0 0.0", "Kd 1.0 1.0 1.0", "Ks 0.0 0.0 0.0",
           f"map_Kd {name}.png"]

    with open(stem + ".obj", "w") as f:
        f.write("\n".join(obj) + "\n")
    with open(stem + ".mtl", "w") as f:
        f.write("\n".join(mtl) + "\n")
    with open(stem + ".png", "wb") as f:
        f.write(png_bytes)
    print("wrote", stem + ".obj (+ .mtl + .png)")


# --- GLB writer (geometry + texture embedded in one binary chunk) ----------
def write_glb(path, png_bytes):
    positions, normals, uvs, indices = cube()

    pos_bytes = b"".join(struct.pack("<3f", *p) for p in positions)
    nrm_bytes = b"".join(struct.pack("<3f", *n) for n in normals)
    uv_bytes = b"".join(struct.pack("<2f", *t) for t in uvs)
    idx_bytes = struct.pack("<%dH" % len(indices), *indices)

    # Pack each accessor's data into one shared buffer, padding to 4 bytes after
    # each view so the next view's byteOffset stays aligned.
    blob = bytearray()
    bufferViews = []

    def push(data, target=None):
        off = len(blob)
        blob.extend(data)
        bv = {"buffer": 0, "byteOffset": off, "byteLength": len(data)}
        if target is not None:
            bv["target"] = target
        # pad the *buffer* to 4 bytes after each view for the next one
        while len(blob) % 4 != 0:
            blob.append(0)
        bufferViews.append(bv)
        return len(bufferViews) - 1

    bv_pos = push(pos_bytes, 34962)
    bv_nrm = push(nrm_bytes, 34962)
    bv_uv = push(uv_bytes, 34962)
    bv_idx = push(idx_bytes, 34963)
    bv_img = push(png_bytes)  # no target -> image data

    mins = [min(p[i] for p in positions) for i in range(3)]
    maxs = [max(p[i] for p in positions) for i in range(3)]

    gltf = {
        "asset": {"version": "2.0", "generator": "make_sample_models.py"},
        "scene": 0,
        "scenes": [{"nodes": [0]}],
        "nodes": [{"mesh": 0, "name": "textured_cube"}],
        "meshes": [{"primitives": [{
            "attributes": {"POSITION": 0, "NORMAL": 1, "TEXCOORD_0": 2},
            "indices": 3, "material": 0}]}],
        "accessors": [
            {"bufferView": bv_pos, "componentType": 5126, "count": len(positions),
             "type": "VEC3", "min": mins, "max": maxs},
            {"bufferView": bv_nrm, "componentType": 5126, "count": len(normals),
             "type": "VEC3"},
            {"bufferView": bv_uv, "componentType": 5126, "count": len(uvs),
             "type": "VEC2"},
            {"bufferView": bv_idx, "componentType": 5123, "count": len(indices),
             "type": "SCALAR"},
        ],
        "bufferViews": bufferViews,
        "buffers": [{"byteLength": len(blob)}],
        "images": [{"bufferView": bv_img, "mimeType": "image/png"}],
        "samplers": [{"magFilter": 9729, "minFilter": 9987,
                      "wrapS": 10497, "wrapT": 10497}],
        "textures": [{"source": 0, "sampler": 0}],
        "materials": [{"pbrMetallicRoughness": {
            "baseColorTexture": {"index": 0},
            "baseColorFactor": [1, 1, 1, 1],
            "metallicFactor": 0.0, "roughnessFactor": 1.0}}],
    }

    json_bytes = json.dumps(gltf, separators=(",", ":")).encode("utf-8")
    json_bytes += b" " * ((4 - len(json_bytes) % 4) % 4)         # pad with spaces
    bin_bytes = bytes(blob)
    bin_bytes += b"\x00" * ((4 - len(bin_bytes) % 4) % 4)        # pad with zeros

    total = 12 + 8 + len(json_bytes) + 8 + len(bin_bytes)
    with open(path, "wb") as f:
        f.write(struct.pack("<III", 0x46546C67, 2, total))      # "glTF", ver 2
        f.write(struct.pack("<II", len(json_bytes), 0x4E4F534A))  # JSON chunk
        f.write(json_bytes)
        f.write(struct.pack("<II", len(bin_bytes), 0x004E4942))   # BIN chunk
        f.write(bin_bytes)
    print("wrote", path)


PALETTE_A = ((220, 60, 60), (60, 200, 90), (70, 110, 220), (230, 200, 70))
PALETTE_B = ((230, 130, 50), (40, 180, 180), (150, 80, 200), (230, 90, 150))


def ensure_dir(p):
    os.makedirs(p, exist_ok=True)


def main():
    models = os.path.join(ROOT, "models")
    assets = os.path.join(ROOT, "tests", "assets")
    ensure_dir(models)
    ensure_dir(assets)

    png_a = quadrant_texture(PALETTE_A)
    png_b = quadrant_texture(PALETTE_B)

    # Shipped sample models: one OBJ cube and one (differently-colored) GLB cube,
    # so the staged scene shows both loaders working with distinct textures.
    write_obj(os.path.join(models, "textured_cube"), png_a, PALETTE_A)
    write_glb(os.path.join(models, "textured_cube.glb"), png_b)

    # Headless loader-test fixtures.
    write_obj(os.path.join(assets, "cube"), png_a, PALETTE_A)
    write_glb(os.path.join(assets, "cube.glb"), png_a)


if __name__ == "__main__":
    main()
